
project_id = "xxccvppbxnhowncdhvdi"

[functions.slack-auth]
verify_jwt = false

[functions.slack-callback]
verify_jwt = false

[functions.calendar-auth]
verify_jwt = false

[functions.calendar-callback]
verify_jwt = false

[functions.gmail-auth]
verify_jwt = false

[functions.gmail-callback]
verify_jwt = false

[functions.fetch-calendar-events]
verify_jwt = false

[functions.fetch-gmail-emails]
verify_jwt = false

[functions.fetch-slack-messages]
verify_jwt = false

[functions.chief-data-collector]
verify_jwt = false

[functions.chief-summary]
verify_jwt = true

[functions.setup-chief-cron]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.manage-calendar]
verify_jwt = true

[functions.send-slack-message]
verify_jwt = true

[functions.task-scheduler]
verify_jwt = false

[functions.chief-ai-chat]
verify_jwt = true

[functions.realtime-voice-chief]
verify_jwt = false
