
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyvsexfagfpefuniknto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5dnNleGZhZ2ZwZWZ1bmlrbnRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDAxMjgsImV4cCI6MjA2NDc3NjEyOH0.mLaz5I6VlbRolG5ulSYbm6kPb90JdG7AHL4rQLyX9G0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
